require 'google_web_translate/version.rb'
require 'google_web_translate/string_escaping.rb'
require 'google_web_translate/http_client.rb'
require 'google_web_translate/result.rb'
require 'google_web_translate/api.rb'
